# Generated by Django 2.1.2 on 2018-10-27 06:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0004_post_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='team',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GEODESY', 'geodesy'), ('ROCK MECHANICS', 'rock mechanics'), ('MODELING', 'modeling')], default='exit', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='team',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GEODESY', 'geodesy'), ('ROCK MECHANICS', 'rock mechanics'), ('MODELING', 'modeling')], max_length=31),
        ),
    ]
