# Generated by Django 2.1.2 on 2018-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0005_auto_20181027_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='author',
            new_name='uploaded_by',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.CharField(default='exit', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='authors',
            field=models.CharField(default='exit', max_length=250),
            preserve_default=False,
        ),
    ]
