# Generated by Django 2.1.2 on 2018-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0010_auto_20181028_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='post',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.RemoveField(
            model_name='research',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='research',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='research',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='research',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='research',
            name='authors',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
