# Generated by Django 2.1.2 on 2018-10-28 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0012_auto_20181028_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='research',
            name='year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
