# Generated by Django 2.1.2 on 2018-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0013_auto_20181028_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='publication_pics'),
        ),
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='research_pics'),
        ),
    ]
