# Generated by Django 2.1.2 on 2018-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0015_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, default='Journal', max_length=250),
        ),
    ]
