# Generated by Django 2.1.2 on 2018-11-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultquakes', '0017_auto_20181112_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
