# Generated by Django 2.1.2 on 2018-11-13 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faultquakes', '0018_auto_20181113_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geodesy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title', max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='geodesy_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title', max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='modeling_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title', max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='rock_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
