# Generated by Django 2.1.2 on 2018-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswall',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='news_pics'),
        ),
        migrations.AddField(
            model_name='newswall',
            name='video',
            field=models.URLField(default='exit'),
            preserve_default=False,
        ),
    ]
