# Generated by Django 2.1.2 on 2018-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181112_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswall',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_pics'),
        ),
        migrations.AlterField(
            model_name='newswall',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
