# Generated by Django 2.1.2 on 2018-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_auto_20181025_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='author',
            new_name='uploaded_by',
        ),
    ]
