# Generated by Django 2.1.2 on 2018-11-02 09:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_auto_20181027_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_posted',
            new_name='deadline',
        ),
        migrations.AddField(
            model_name='job',
            name='lab_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Within', 'Within'), ('Outside', 'Outside')], default='exit', max_length=13),
            preserve_default=False,
        ),
    ]
