from django.urls import path
from .views import (
                    PostListView,
                    PublicationsListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView,
                    ResearchListView,
                    UserResearchListView,
                    ResearchDetailView,
                    ResearchCreateView,
                    ResearchUpdateView,
                    ResearchDeleteView,
                    GeodesyListView,
                    UserGeodesyListView,
                    GeodesyDetailView,
                    GeodesyCreateView,
                    GeodesyUpdateView,
                    GeodesyDeleteView,
                    ModelingListView,
                    UserModelingListView,
                    ModelingDetailView,
                    ModelingCreateView,
                    ModelingUpdateView,
                    ModelingDeleteView,
                    RockListView,
                    UserRockListView,
                    RockDetailView,
                    RockCreateView,
                    RockUpdateView,
                    RockDeleteView,
                    MembersListView,
                    NewswallListView,
                    NewswallDetailView,
                    NewswallCreateView,
                    NewswallUpdateView,
                    NewswallDeleteView,
                    UserNewswallListView,
                    IndexView)
from . import views




urlpatterns = [
    path('news/', NewswallListView.as_view(), name='news'),
    path('news/<int:pk>/', NewswallDetailView.as_view(), name='news-detail'),
    path('news/new/', NewswallCreateView.as_view(), name='news-create'),
    path('news/<int:pk>/update/', NewswallUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewswallDeleteView.as_view(), name='news-delete'),
    path('news/user/<str:username>', UserNewswallListView.as_view(), name='user-news'),
    path('user/members/', MembersListView.as_view(), name='members'),
    path('publications/', PublicationsListView.as_view(), name='publications'),
    path('research/', ResearchListView.as_view(), name='research'),
    path('geodesy/', GeodesyListView.as_view(), name='geodesy'),
    path('modeling/', ModelingListView.as_view(), name='modeling'),
    path('rock/', RockListView.as_view(), name='rock'),
    path('research/user/<str:username>', UserResearchListView.as_view(), name='user-research'),
    path('research/<int:pk>/', ResearchDetailView.as_view(), name='research-detail'),
    path('research/new/', ResearchCreateView.as_view(), name='research-create'),
    path('research/<int:pk>/update/', ResearchUpdateView.as_view(), name='research-update'),
    path('research/<int:pk>/delete/', ResearchDeleteView.as_view(), name='research-delete'),
    path('geodesy/user/<str:username>', UserGeodesyListView.as_view(), name='user-geodesy'),
    path('geodesy/<int:pk>/', GeodesyDetailView.as_view(), name='geodesy-detail'),
    path('geodesy/new/', GeodesyCreateView.as_view(), name='geodesy-create'),
    path('geodesy/<int:pk>/update/', GeodesyUpdateView.as_view(), name='geodesy-update'),
    path('geodesy/<int:pk>/delete/', GeodesyDeleteView.as_view(), name='geodesy-delete'),
    path('modeling/user/<str:username>', UserModelingListView.as_view(), name='user-modeling'),
    path('modeling/<int:pk>/', ModelingDetailView.as_view(), name='modeling-detail'),
    path('modeling/new/', ModelingCreateView.as_view(), name='modeling-create'),
    path('modeling/<int:pk>/update/', ModelingUpdateView.as_view(), name='modeling-update'),
    path('modeling/<int:pk>/delete/', ModelingDeleteView.as_view(), name='modeling-delete'),
    path('rock/user/<str:username>', UserRockListView.as_view(), name='user-rock'),
    path('rock/<int:pk>/', RockDetailView.as_view(), name='rock-detail'),
    path('rock/new/', RockCreateView.as_view(), name='rock-create'),
    path('rock/<int:pk>/update/', RockUpdateView.as_view(), name='rock-update'),
    path('rock/<int:pk>/delete/', RockDeleteView.as_view(), name='rock-delete'),
    path('post/user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('map/', views.map, name='faultquakes-map'),
    path('', IndexView.as_view(), name='faultquakes-index'),
]